const ItemsData = [
    {
      id: "1",
      title: "Super new Sneakers",
      actual_price: "30.00",
      des_price: "6.00",
      sub_total:"6",
      description: "The best sneakers you would ever find.",
      pic: "../img/01.jpg",
      offer: "80% Off",
      rating: "4/5",
    },
    {
        id: "2",
        title: "Magical Earrings",
        actual_price: "170.00",
        des_price: "150.00",
        sub_total:"150",
        description: "The best sneakers you would ever find.",
        pic: "../img/15.jpg",
        offer: "12% Off",
        rating: "4/5",
      },
      {
        id: "3",
        title: "Pack It On Your Back",
        actual_price: "200.00",
        des_price: "150.00",
        sub_total:"150",
        description: "The best sneakers you would ever find.",
        pic: "../img/13.jpg",
        offer: "25% Off",
        rating: "4/5",
      },
     
      {
        id: "4",
        title: "Fancy Shades",
        actual_price: "420.00",
        des_price: "420.00",
        sub_total:"420",
        description: "The best sneakers you would ever find.",
        pic: "../img/03.jpg",
        offer: "0% Off",
        rating: "4/5",
      },
      {
        id: "5",
        title: "Yellow Watch",
        actual_price: "400.00",
        des_price: "330.00",
        sub_total:"330",
        description: "The best sneakers you would ever find.",
        pic: "../img/27.jpg",
        offer: "18% Off",
        rating: "4/5",
      },
      {
        id: "6",
        title: "Famous Blue Bag",
        actual_price: "750.00",
        des_price: "750.00",
        sub_total:"750",
        description: "The best sneakers you would ever find.",
        pic: "../img/02.jpg",
        offer: "0% Off",
        rating: "4/5",
      },
      {
        id: "7",
        title: "Retro Trainer",
        actual_price: "200.00",
        des_price: "175.00",
        sub_total:"175",
        description: "The best sneakers you would ever find.",
        pic: "../img/06.jpg",
        offer: "13% Off",
        rating: "4/5",
      },
      {
        id: "8",
        title: "Seven Mile Sneakers",
        actual_price: "200.00",
        des_price: "100.00",
        sub_total:"100",
        description: "The best sneakers you would ever find.",
        pic: "../img/11.jpg",
        offer: "50% Off",
        rating: "4/5",
      },

]
    export default ItemsData;